- hosts: tomcat
  become: True
  tasks:
    - name: Download from nexus3
      maven_artifact:
        group_id: in.javahome
        artifact_id: devops-app
        repository_url: http://172.31.45.220:8081/repository/devops-app/'
        username: admin
        password: <your-secret-password>
        dest: ./devops-app.war
        version: 1.4
    - name: Deploy war file to tomcat
      copy:
        src: ./devops-app.war
        dest: /opt/tomcat9/webapps/
