- hosts: tomcat
  become: True
  tasks:
    - name: Deploy war file to tomcat
      copy:
        src: /Users/kammana/.jenkins/workspace/devops-mini-project-april124/target/devops-app.war
        dest: /opt/tomcat9/webapps/
